version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: power-project-app
    container_name: power-project-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - power-project-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: power-project-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - power-project-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: power-project-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: power_project
      POSTGRES_USER: power_user
      POSTGRES_PASSWORD: power_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - power-project-network

  redis:
    image: redis:alpine
    container_name: power-project-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - power-project-network

  node:
    image: node:18-alpine
    container_name: power-project-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - power-project-network

  adminer:
    image: adminer:latest
    container_name: power-project-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - power-project-network
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local

networks:
  power-project-network:
    driver: bridge
